---
#playbook test
- hosts: servers
  remote_user: root

  tasks:

    - name: Install snmp
      yum:
        name: net-snmp

    - name: Install alpine
      yum:
        name: alpine

    - name: Install nmap
      yum:
        name: nmap

    - name: Install wget
      yum:
        name: wget

    - name: Install logrotate
      yum:
        name: logrotate

    - name: Install logwatch
      yum:
        name: httpd

    - name: Install httpd
      yum:
        name: httpd

    - name: Install mariadb
      yum:
        name: mariadb

    - name: Install mariadb-server
      yum:
        name: mariadb-server

    - name: Install subversion
      yum:
        name: subversion

    - name: Install git
      yum:
        name: git

    - name: Install mod_ssl
      yum:
        name: mod_ssl

    - name: start and enable mariadb
      systemd:
        name: mariadb
        enabled: yes
        state: started

    - name: start and enable apache
      systemd:
        name: httpd
        enabled: yes
        state: started

    - name: start and enable net-snmp
      systemd:
        name: snmpd
        enabled: yes
        state: started

    - name: configure firewalld for mariadb
      firewalld:
        service: mysql
        permanent: yes
        state: enabled

    - name: configure firewalld for apache
      firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: configure firewalld for net-snmp
      firewalld:
        service: snmp
        permanent: yes
        state: enabled
